"""
Django settings for blogproject project.

Generated by 'django-admin startproject' using Django 6.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
from decouple import config
import cloudinary
import dj_database_url
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
#SECRET_KEY = 'django-insecure-zaqkz21)mii^r^t43c7sp0!2nax#n@@-k5scy2s2h9*i=6hx6('
SECRET_KEY = config('SECRET_KEY')

cloudinary.config(
    api_key = config('CLOUDINARY_API_KEY'),
    api_secret = config('CLOUDINARY_API_SECRET'),
    cloud_name = config('CLOUDINARY_CLOUD_NAME')
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

#ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'myapp',
    'cloudinary',
    'django_registration',
    'rest_framework',
    'rest_framework.authtoken',
    'products',
    'customers',
    'orders',
    'cart',
    'drf_yasg',
    'rest_framework_simplejwt',
    'corsheaders',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    #cors
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'blogproject.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'blogproject.wsgi.application'

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
#gmail app passwords
EMAIL_HOST = config('EMAIL_HOST')
EMAIL_PORT = config('EMAIL_PORT')
EMAIL_USE_TLS = config('EMAIL_USE_TLS')
EMAIL_HOST_USER = config('EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD = config('EMAIL_HOST_PASSWORD')

# auth drf authenticate api test broweser vs postman 260126
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.SessionAuthentication',  # Good for browser testing
        'rest_framework.authentication.TokenAuthentication',    # Good for mobile/external apps
        'rest_framework_simplejwt.authentication.JWTAuthentication',    # JWT token
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated', # Everything is locked by default
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 5,  # Default page size
    #versioning
    'DEFAULT_VERSIONING_CLASS':'rest_framework.versioning.URLPathVersioning',
    'DEFAULT_VERSION': 'v1',
    'ALLOWED_VERSIONS':['v1', 'v2'],
    'VERSION_PARAMS': 'version',
    #api rate throttling
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.UserRateThrottle',
        'rest_framework.throttling.AnonRateThrottle'
    ],
    #how many from a given user
    'DEFAULT_THROTTLE_RATES': {
        'user': '100/day',
        'anon': '10/day'
    }
}

#cors step 3
CORS_ALLOW_ALL_ORIGINS = True # for development not prod

#for specific origins like react # recommended for prod
CORS_ALLOWED_ORIGINS = [
    'https://blogproject-django-zindua-learn.onrender.com'
    #'https://example.com',# parse in domain here
    #'https://sub.example.com',# additonals
]

#render
ALLOWED_HOSTS = ['blogproject-django-zindua-learn.onrender.com', '127.0.0.1']

#addition al setting for headers token
CORS_ALLOW_CREDENTIALS = True

    #accepted headers
CORS_ALLOW_HEADERS = [
    'content-type',
    'authorization',
    'x-csrftoken'
]

#encryted field
#ENCRYPTED_FIELDS_KEY = 'your-secret-encryption-key'
# python -c "from cryptography.fernet import Fernet; print(Fernet.generate_key().decode())"

FIELD_ENCRYPTION_KEY = '5yKdb6EYMNpZwOikXfL09cg_x6qmG-fGZN5896HHEDU='

# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }

# DATABASES = {
#     'default': {
#          'ENGINE': 'django.db.backends.postgresql',
#          'NAME': config('DATABASE_NAME'), #add name of db created
#          'USER': config('DATABASE_USER'), #username autocreated
#          'PASSWORD': config('DATABASE_PASSWORD'),
#          'HOST': config('DATABASE_HOST'),
#          'PORT': config('PORT')
#     }
# }

# for online we use render online postgres
# DATABASES = {
#     'default': dj_database_url.config(
#         default=config('INTERNAL_DATABASE_URL'), # fallback for local development
#         conn_max_age=600,
#         conn_health_checks=True
#     )
# }
# This logic checks if 'INTERNAL_DATABASE_URL' exists (Render). 
# If not, it falls back to local SQLite so you don't get errors on your laptop.


if os.environ.get('INTERNAL_DATABASE_URL'):
    DATABASES = {
        'default': dj_database_url.config(
            default=os.environ.get('INTERNAL_DATABASE_URL'),
            conn_max_age=600,
            conn_health_checks=True
        )
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }



# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

#STATIC_URL = 'static/'
STATIC_URL = '/static/'
#STATIC_ROOT = 'static/'
#for os use
STATIC_FILES_DIR = [os.path.join(BASE_DIR, 'static')]
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

#configure login redirect
LOGIN_REDIRECT_URL = '/'
LOGIN_URL = 'login'
LOGOUT_REDIRECT_URL = 'login'

#set custom User Model
AUTH_USER_MODEL = 'myapp.CustomUser'

#Authentication backend
AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
    'myapp.backends.CustomEmailBackend'
]

# to auto add slashes to say there is more after
APPEND_SLASH = True