# Generated by Django 6.0.1 on 2026-01-22 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='first name')),
                ('last_name', models.CharField(max_length=50, verbose_name='last name')),
                ('email', models.EmailField(max_length=254, verbose_name='customer email')),
                ('age', models.IntegerField(verbose_name='age of customer')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('N', 'Prefer not to say')], default='N', max_length=1, verbose_name='customers gender')),
                ('city', models.CharField(max_length=50, verbose_name='city located')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='date joined')),
            ],
        ),
    ]
