# Generated by Django 6.0.1 on 2026-01-22 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='product name')),
                ('description', models.TextField(verbose_name='description')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='product price')),
                ('stock', models.IntegerField(verbose_name='amount of products')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='when product was created')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='when stock was increased')),
            ],
        ),
    ]
